### ISSUE TITLE
Custom separator

### ISSUE THREAD

**Issue by piratuks** [piratuks/typescript-event-emitter#64]
Implement option to have custom separator

**Comment by mahesh-gunjal** [comment]
@piratuks can you eloborate about the issue in this thread to get the clear idea of what needs to be done here ?

**Comment by piratuks** [comment]
@mahesh-gunjal Sure. So the default separator is ".". So if the event listener listens to "namespace.someevent" it is separated by ".". The idea is to implement an option for EventEmitter which allows to set a custom separator for all listeners and to implement an additional prop for "on" to accept separator which is for that particular listener. So basically if the listener contains its custom separator then global separator prop should be overridden otherwise global should be used if provided. If no separator have been provided then default should be used.

So for example 

const eventEmitter: EventEmitter = new EventEmitter({ separator: ':' });
eventEmitter.on("namespace-someEvent", () => {}, { separator: "-" }); //uses the listener one -
eventEmitter.on("namespace:someEvent", () => {}); //uses the global one :

const eventEmitter: EventEmitter = new EventEmitter();
eventEmitter.on("namespace.someEvent", () => {});  //uses the default .


Something along those lines is the initial idea. Also need to keep in mind that GlobalEventBus should have an option to change global separator aswell if its done via constructor and etc.
