### ISSUE TITLE
typescript-event-emitter node_modules package has to .js files

### ISSUE THREAD

**Issue by st-clair-clarke** [piratuks/typescript-event-emitter#75]
Hi,
I installed typescript-event-emitter as shown below:

```
pnpm add typescript-event-emitter
```

I tried to import EventEmitter as follows:

```
import {EventEmitter} from 'typescript-event-emitter'
```

However, the EventEmitter could not be found.

I looked at the node_modules typescript-event-emitter the result is shown in the screenshot below:

![image](https://github.com/piratuks/typescript-event-emitter/assets/3227590/aab840ad-5a18-4c1d-8d06-52fc15ef148a)

There actually is no modules to import in the package.

I uninstalled and installed the package with the same result.

Please do take a look at the package. All my other installed packages work fine.

Cheers

**Comment by piratuks** [comment]
#[st-clair-clarke](https://github.com/st-clair-clarke) Hello, thank you for noticing and notifying me. The issue is that 2.0.1 got published without a proper distribution folder. It has been republished with 2.0.2.

**Comment by st-clair-clarke** [comment]
Thanks.
